# POS access, PIN reset, location scoping, location <-> cost center, Retail/F&B per location.
# Runs inside a transaction that is NEVER committed and ALWAYS rolled back (commit is disabled below), so the
# tenant's real rows are untouched — it creates its own ZZ users, registers and locations and they vanish at the end.
# Run from /home/frappe/innovegic-bench/sites:  ../env/bin/python /home/xentraerp/scripts/pos-checks/access_location_suite.py
import sys, frappe
frappe.init(site="197349.xentraerp.local", sites_path="/home/frappe/innovegic-bench/sites"); frappe.connect(); frappe.set_user("Administrator")
frappe.db.commit = lambda *a, **k: None          # nothing below can be committed; the run always ends in rollback
from custom_erp.api import pos, pos_core as core
P, F = [], []
def check(n, c, d=""): (P if c else F).append(n); print(("  PASS " if c else "  FAIL ") + n + (f"  [{d}]" if d and not c else ""))
def err(fn, sub):
    try: fn()
    except Exception as e: return sub.lower() in str(e).lower()
    return False
try:
    reg = frappe.get_all("POS Profile", pluck="name")[0]
    u = "zz.pin.test@example.com"
    frappe.get_doc({"doctype":"User","email":u,"first_name":"ZZ Pin Test","send_welcome_email":0,"enabled":1}).insert(ignore_permissions=True)
    a = pos.get_pos_access(u)
    check("new user: no PIN, no POS role", not a["has_pin"] and not a["active"] and a["pos_role"] is None)
    check("panel data lists roles, registers and PIN length", len(a["pos_roles"]) == 4 and reg in [r["name"] for r in a["registers"]] and (a["pin_min"], a["pin_max"]) == (6, 8))
    check("register can't be set before a PIN exists", err(lambda: pos.save_pos_access(u, pos_profile=reg), "set a pin first"))
    check("switch can't be flipped before a PIN exists", err(lambda: pos.save_pos_access(u, active=0), "set a pin first"))
    r = pos.reset_pin(u)
    check("reset_pin returns a 6-digit PIN", r["pin"].isdigit() and len(r["pin"]) == 6)
    a = pos.get_pos_access(u)
    check("…stores only its hash and switches it on", frappe.db.get_value("XentraERP POS PIN", u, "pin_hash") == pos._hash_pin(r["pin"]) and a["active"])
    check("…and a brand-new user becomes a Waiter (least privilege)", a["pos_role"] == "POS Waiter" and a["level"] == "waiter")
    check("get_pos_access never returns the PIN or hash", r["pin"] not in str(a) and "pin_hash" not in a)
    r2 = pos.reset_pin(u)
    check("second reset replaces the PIN (old hash gone)", frappe.db.get_value("XentraERP POS PIN", u, "pin_hash") == pos._hash_pin(r2["pin"]))
    a = pos.save_pos_access(u, pos_role="POS Cashier", pos_profile=reg)
    check("role → Cashier and register locked", a["pos_role"] == "POS Cashier" and a["pos_profile"] == reg)
    check("PIN unchanged by save_pos_access", frappe.db.get_value("XentraERP POS PIN", u, "pin_hash") == pos._hash_pin(r2["pin"]))
    a = pos.save_pos_access(u, pos_profile="")
    check("empty register clears the lock", a["pos_profile"] is None)
    a = pos.save_pos_access(u, active=0)
    check("switch PIN off", a["has_pin"] and not a["active"])
    check("unknown role refused", err(lambda: pos.save_pos_access(u, pos_role="POS Boss"), "unknown pos role"))
    check("unknown register refused", err(lambda: pos.save_pos_access(u, pos_profile="Nope"), "no such register"))
    check("reset switches the PIN back on and keeps the Cashier role", pos.reset_pin(u) and pos.get_pos_access(u)["active"] and pos.get_pos_access(u)["pos_role"] == "POS Cashier")
    pos.set_pin(u, "482913")
    check("set_pin with an unused PIN works", frappe.db.get_value("XentraERP POS PIN", u, "pin_hash") == pos._hash_pin("482913"))
    u2 = "zz.pin.test2@example.com"
    frappe.get_doc({"doctype":"User","email":u2,"first_name":"ZZ Two","send_welcome_email":0,"enabled":1}).insert(ignore_permissions=True)
    check("two people can't share a PIN", err(lambda: pos.set_pin(u2, "482913"), "already in use"))
    notes = frappe.get_all("Comment", filters={"reference_doctype":"User","reference_name":u,"comment_type":"Info"}, pluck="content")
    check("changes are noted on the user, without any PIN", len(notes) >= 4 and not any(r["pin"] in n or "482913" in n for n in notes), str(notes))
    adm = "Administrator"
    check("an administrator's role can't be overwritten", err(lambda: pos.save_pos_access(adm, pos_role="POS Cashier"), "administrator"))
    # non-admins are refused, whatever their POS role
    for role in ("POS Waiter", "POS Cashier", "POS Supervisor"):
        pos.save_pos_access(u, pos_role=role, active=1)
        frappe.set_user(u)
        check(f"{role} can't read POS access", err(lambda: pos.get_pos_access(u2), "administrator"))
        check(f"{role} can't reset a PIN", err(lambda: pos.reset_pin(u2), "administrator"))
        check(f"{role} can't change a role", err(lambda: pos.set_pos_role(u2, "POS Cashier"), "administrator"))
        check(f"{role} can't list staff", err(pos.list_pos_users, "administrator"))
        frappe.set_user("Administrator")
    # ---------------------------------------------------- location scoping
    print("== location scoping")
    company = frappe.get_all("Company", pluck="name")[0]
    cc = frappe.get_all("Cost Center", filters={"is_group": 0}, pluck="name")[0]
    def mkreg(n):
        return frappe.get_doc({"doctype":"POS Profile","name":n,"company":company,"warehouse":"Stores - JC","currency":"BHD","customer":"Test Customer","selling_price_list":"Standard Selling","payments":[{"mode_of_payment":"Cash","default":1}],"write_off_account":"Write Off - JC","write_off_cost_center":"Main - JC","account_for_change_amount":"Cash - JC"}).insert(ignore_permissions=True).name
    ra, rb = mkreg("ZZ Loc Reg A"), mkreg("ZZ Loc Reg B")
    core.save_location("ZZA", "ZZ Branch A", cc, None, [ra]); core.save_location("ZZB", "ZZ Branch B", cc, None, [rb])
    print("== location ↔ cost center")
    check("a location needs a cost center", err(lambda: core.save_location("ZZC", "No CC"), "cost center"))
    grp = frappe.get_all("Cost Center", filters={"is_group": 1}, pluck="name")[0]
    check("a group cost center is refused", err(lambda: core.save_location("ZZC", "Group CC", grp), "is a group"))
    check("a made-up cost center is refused", err(lambda: core.save_location("ZZC", "Bad CC", "Nope - XX"), "no such cost center"))
    core.save_location("ZZC", "Has CC", cc)
    lc = frappe.get_doc("XentraERP POS Location", "ZZC")
    check("company follows the cost center", lc.company == frappe.db.get_value("Cost Center", cc, "company") and lc.cost_center == cc)
    low = frappe.get_doc({"doctype": "XentraERP POS Location", "location_code": "zzlow", "location_name": "Typed in ERP", "cost_center": cc}).insert(ignore_permissions=True)
    check("a code typed in the ERP app is upper-cased into the name", low.name == "ZZLOW" and low.location_code == "ZZLOW")
    check("a bad code typed in the ERP app is refused", err(lambda: frappe.get_doc({"doctype": "XentraERP POS Location", "location_code": "bad code!", "location_name": "x", "cost_center": cc}).insert(ignore_permissions=True), "2-8 letters"))
    check("saving without a cost center in the ERP app is refused", err(lambda: frappe.get_doc({"doctype": "XentraERP POS Location", "location_code": "ZZNCC", "location_name": "x"}).insert(ignore_permissions=True), "cost center"))
    lu = "zz.loc.user@example.com"
    frappe.get_doc({"doctype":"User","email":lu,"first_name":"ZZ Loc","send_welcome_email":0,"enabled":1}).insert(ignore_permissions=True)
    pos.set_pin(lu, "135790", None, 1, "POS Supervisor", "ZZA")
    a = pos.get_pos_access(lu)
    check("location saved with the PIN", a["location"] == "ZZA" and a["effective_location"] == "ZZA")
    check("panel gets the location's cost center", a["cost_center"] == cc and {l["code"] for l in a["locations"]} >= {"ZZA", "ZZB"})
    check("registers carry their location", {r["name"]: r["location"] for r in a["registers"]}.get(ra) == "ZZA" and {r["name"]: r["location"] for r in a["registers"]}.get(rb) == "ZZB")
    check("a register from another location is refused", err(lambda: pos.save_pos_access(lu, pos_profile=rb), "doesn't belong to location"))
    check("…and so is a nonexistent location", err(lambda: pos.save_pos_access(lu, location="NOPE"), "no such location"))
    check("moving to B while locked to a register at A is refused", err(lambda: pos.save_pos_access(lu, pos_profile=ra, location="ZZB"), "doesn't belong"))
    check("location + matching register saves", pos.save_pos_access(lu, pos_profile=ra, location="ZZA")["pos_profile"] == ra)
    check("users list shows the location", any(x["user"] == lu and x["location"] == "ZZA" for x in pos.list_pos_users()))
    pos.save_pos_access(lu, pos_profile="")
    frappe.set_user(lu)
    check("their register list is only their location's", [p["name"] for p in pos.list_pos_profiles()] == [ra], str([p["name"] for p in pos.list_pos_profiles()]))
    check("using a register at their location works", core.get_profile(ra).name == ra)
    check("using another location's register is refused", err(lambda: core.get_profile(rb), "you work at location zza"))
    check("settings tell the app their location", core.get_pos_settings()["location"] == "ZZA")
    check("the day-end report is always their own location's", core.end_of_day_report(location="ZZB")["location"] == "ZZA")
    check("another location's shift can't be read or closed", err(lambda: core.require_user_location("ZZB"), "you work at zza") and not err(lambda: core.require_user_location("ZZA"), "x"))
    frappe.set_user("Administrator")
    check("an administrator isn't tied to a location", core.user_location("Administrator") is None and core.get_profile(rb).name == rb)
    check("admin's report can still pick a location", core.end_of_day_report(location="ZZB")["location"] == "ZZB")
    pos.save_pos_access(lu, location="")
    check("clearing the location frees them", core.user_location(lu) is None)
    pos.save_pos_access(lu, pos_profile=ra)
    check("with no location, the register they're locked to decides it", core.user_location(lu) == "ZZA")
    pos.save_pos_access(lu, pos_profile="")
    frappe.set_user(lu)
    check("with neither, every register is offered", {ra, rb} <= {p["name"] for p in pos.list_pos_profiles()})
    frappe.set_user("Administrator")
    # ---------------------------------------------------- Retail / F&B per location
    print("== Retail / F&B per location")
    from custom_erp.api import pos_fnb as fnb
    frappe.db.set_single_value("XentraERP POS Settings", "require_shift", 0)
    frappe.db.set_single_value("XentraERP POS Settings", "pos_mode", "Retail")     # tenant-wide default = Retail
    rc = mkreg("ZZ Mode Reg C"); rd = mkreg("ZZ Mode Reg D"); re_ = mkreg("ZZ Mode Reg E")
    core.save_location("ZZF", "F&B only", cc, None, [rc], 0, 0, 1)
    core.save_location("ZZR", "Retail only", cc, None, [rd], 0, 1, 0)
    core.save_location("ZZBOTH", "Both", cc, None, [re_], 0, 1, 1)
    check("modes: F&B-only location", core.modes_for(rc) == ["F&B"])
    check("modes: Retail-only location", core.modes_for(rd) == ["Retail"])
    check("modes: a location can run both", core.modes_for(re_) == ["F&B", "Retail"])
    lonely = mkreg("ZZ Mode Lonely")
    check("modes: no location → tenant-wide mode", core.modes_for(lonely) == ["Retail"])
    check("a location must run at least one kind of POS", err(lambda: core.save_location("ZZN", "None", cc, None, [], 0, 0, 0), "at least one"))
    check("…also when saved in the ERP app", err(lambda: frappe.get_doc({"doctype": "XentraERP POS Location", "location_code": "ZZN2", "location_name": "x", "cost_center": cc, "enable_retail": 0, "enable_fnb": 0}).insert(ignore_permissions=True), "at least one"))
    core.save_location("ZZF", "F&B only", cc, None, [rc])
    check("leaving the switches out keeps them", core.modes_for(rc) == ["F&B"])
    core.save_location("ZZNEW", "New under Retail tenant", cc, None, [])
    check("a new location starts Retail-only when the tenant is in Retail mode", frappe.db.get_value("XentraERP POS Location", "ZZNEW", ["enable_retail", "enable_fnb"]) == (1, 0))
    st = core.get_pos_settings(rc)
    check("settings for an F&B-only register", st["modes"] == ["F&B"] and st["pos_mode"] == "F&B" and st["global_mode"] == "Retail")
    check("settings for a Retail-only register", core.get_pos_settings(rd)["pos_mode"] == "Retail")
    check("settings for a both-modes register", core.get_pos_settings(re_)["modes"] == ["F&B", "Retail"])
    frappe.db.sql("delete from `tabXentraERP POS Table` where name like 'ZZM-%'")
    fnb.save_table("ZZM-1", "Main", 4, 0, 0, "ZZF"); fnb.save_table("ZZM-2", "Main", 4, 0, 0, "ZZBOTH"); fnb.save_table("ZZM-3", "Main", 4, 0, 0, "ZZR")
    o = fnb.open_order("ZZM-1", rc, 1)
    check("F&B works at the F&B-only location (though the tenant-wide mode is Retail)", o["status"] == "Open")
    check("…and at the both-modes location", fnb.open_order("ZZM-2", re_, 1)["status"] == "Open")
    check("F&B is refused at the Retail-only location", err(lambda: fnb.open_order("ZZM-3", rd, 1), "table service isn't enabled at location zzr"))
    check("F&B is refused for a register with no location under a Retail tenant", err(lambda: fnb.open_order("ZZM-1", lonely, 1), "table service isn't enabled"))
    check("list_tables follows the register's location too", err(lambda: fnb.list_tables(rd), "table service") and len(fnb.list_tables(rc)) >= 1)
    frappe.db.set_value("Item", "Blue Pen", "is_stock_item", 0)   # inside the rolled-back transaction, like the other suites
    item = "Blue Pen"
    sale = lambda reg: core.retail_checkout(reg, [{"item_code": item, "qty": 1}], [{"mode_of_payment": "Cash", "tendered": 1000}])
    check("counter sales work at the Retail-only location", sale(rd)["invoice"])
    check("…and at the both-modes location", sale(re_)["invoice"])
    check("counter sales are refused at the F&B-only location", err(lambda: sale(rc), "counter sales isn't enabled at location zzf"))
    check("cancel works for an order at its own location's mode", fnb.cancel_order(o["name"])["success"])
    # a person tied to a location can't touch another location's orders
    ob = fnb.open_order("ZZM-2", re_, 1)
    pos.set_pin(lu, "246813", None, 1, "POS Supervisor", "ZZF")
    frappe.set_user(lu)
    check("a person at ZZF can't cancel a ZZBOTH order", err(lambda: fnb.cancel_order(ob["name"]), "you work at zzf"))
    check("…and their own location's modes apply without naming a register", core.modes_for() == ["F&B"])
    frappe.set_user("Administrator")
    frappe.db.set_single_value("XentraERP POS Settings", "pos_mode", "F&B")
    check("tenant-wide F&B mode keeps counter sales for registers with no location (as before)", core.modes_for(lonely) == ["F&B", "Retail"])
    core.save_location("ZZNEW2", "New under F&B tenant", cc, None, [])
    check("a new location starts F&B + Retail when the tenant is in F&B mode", frappe.db.get_value("XentraERP POS Location", "ZZNEW2", ["enable_retail", "enable_fnb"]) == (1, 1))
    frappe.db.set_single_value("XentraERP POS Settings", "pos_mode", "Retail")
    check("supervisor no longer has a 'staff' capability", "staff" not in core.CAPS["supervisor"] and "staff" not in core.CAPS["admin"])
finally:
    frappe.db.rollback()
    print(f"\n{len(P)} passed, {len(F)} failed")
    if F: print("FAILED:", F); sys.exit(1)
